CREATE TABLE MEMBER (
    MEMBER_NUM       NUMBER(10)  PRIMARY KEY,
    MEMBER_ID        VARCHAR2(20)    NOT NULL,
    MEMBER_PASSWD    VARCHAR2(20)    NOT NULL,
    MEMBER_NAME      VARCHAR2(20)    NOT NULL,
    MEMBER_DIR       CHAR(1),
    MEMBER_PHONE     VARCHAR2(20)    NOT NULL,
    MEMBER_EMAIL     VARCHAR2(20)    NOT NULL,
    MEMBER_REGDATE   DATE            DEFAULT SYSDATE,
    MEMBER_PHOTO     VARCHAR2(20)    DEFAULT 'img/teamlogo.jpg',
    CLUB_NUM         NUMBER(10)
);

DESC MEMBER;


INSERT INTO MEMBER (MEMBER_NUM, MEMBER_ID, MEMBER_PASSWD, MEMBER_NAME, MEMBER_DIR, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_REGDATE) 
            VALUES (1, 'admin', '1111', '관리자', 'N', '010-1111-1111', 'admin@gmail.com', SYSDATE);

INSERT INTO MEMBER (
    MEMBER_NUM,
    MEMBER_ID,
    MEMBER_PASSWD,
    MEMBER_NAME,
    MEMBER_PHONE,
    MEMBER_EMAIL,
    MEMBER_REGDATE,
    MEMBER_PHOTO
) VALUES (
    MEMBER_SEQ.NEXTVAL,        -- MEMBER_NUM
    'user1',                   -- MEMBER_ID
    '1111',                    -- MEMBER_PASSWD
    '홍길동',                    -- MEMBER_NAME
    '01011117890',             -- MEMBER_PHONE
    'user1@example.com',       -- MEMBER_EMAIL
    TO_DATE('2024-05-21', 'YYYY-MM-DD'), -- MEMBER_REGDATE
    'photo.jpg'                -- MEMBER_PHOTO
);


          
DELETE 
FROM MEMBER
WHERE MEMBER_NUM = 1;

SELECT *
FROM MEMBER;

DROP TABLE MEMBER;


CREATE TABLE FIELD (
	FIELD_NUM	NUMBER(10)	PRIMARY KEY,
	FIELD_NAME	VARCHAR2(20)	NOT NULL,
	FIELD_OLDADDRESS	VARCHAR2(50)	NULL,
	FIELD_NEWADDRESS	VARCHAR2(50)	NULL,
	FIELD_PHONE	VARCHAR2(20)	NOT NULL,
	FIELD_REGDATE	DATE  DEFAULT SYSDATE,
	FIELD_SIZE	VARCHAR2(20)	NOT NULL,
	FIELD_PHOTO	VARCHAR2(50) DEFAULT 'img/teamlogo.jpg',
	FIELD_DAYPRICE	NUMBER	NULL,
	FIELD_ENDPRICE	NUMBER	NULL,
	FIELD_PAYDATE	DATE	NULL,
	FIELD_OPENTIME	VARCHAR2(20)	NOT NULL,
	FIELD_CLOSETIME	VARCHAR2(20)	NOT NULL,
	FIELD_THUMBNAILS	VARCHAR2(50)	 DEFAULT 'img/teamlogo.jpg',
	FIELD_DETAILADDRESS	VARCHAR2(50)	NULL
);

INSERT INTO FIELD (FIELD_NUM, FIELD_NAME, FIELD_OLDADDRESS, FIELD_NEWADDRESS, FIELD_PHONE, FIELD_SIZE,FIELD_PHOTO, FIELD_DAYPRICE, FIELD_ENDPRICE, FIELD_PAYDATE, FIELD_OPENTIME, FIELD_CLOSETIME,FIELD_DETAILADDRESS) 
            VALUES (1, 'Football Field', '123 Old St', '456 New Ave', '010-1234-5678', '100x50m','field1.jpg', 50000, 70000, TO_DATE('2024-05-17', 'YYYY-MM-DD'), '08:00', '20:00','Building 7');

DROP TABLE FIELD;

CREATE TABLE CLUB (
	CLUB_NUM	NUMBER(10)	PRIMARY KEY,
    CLUB_NAME	VARCHAR2(20)	NOT NULL,
	CLUB_INFO	VARCHAR2(100)	NULL,
	CLUB_MEMBERCOUNT	NUMBER(20)	NOT NULL,
	CLUB_PHOTO	VARCHAR2(50) DEFAULT 'img/teamlogo.jpg' ,
	CLUB_LEVEL	VARCHAR2(20)	NOT NULL,
	CLUB_REGDATE	DATE DEFAULT SYSDATE,
	CLUB_LOCATION	VARCHAR2(20) NOT NULL,
	CLUB_PHONE	VARCHAR2(20)	NOT NULL
);

INSERT INTO CLUB (CLUB_NUM, CLUB_NAME, CLUB_INFO, CLUB_MEMBERCOUNT, CLUB_LEVEL, CLUB_LOCATION, CLUB_PHONE) 
        VALUES (1, 'Soccer Club', 'A community soccer club', 50, '하', 'Seoul', '010-1234-5678');

DROP TABLE CLUB;

CREATE TABLE RECORD_FC (
	REC_NO	NUMBER(10)	PRIMARY KEY,
	REC_FID	VARCHAR2(20)	NOT NULL,
	REC_SCO	VARCHAR2(20)	NULL,
	REC_DATE DATE	NULL,
	CLUB_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO RECORD_FC (REC_NO, REC_FID, REC_SCO, REC_DATE, CLUB_NUM) 
       VALUES (1, 'game123', '3-2', TO_DATE('2024-05-17', 'YYYY-MM-DD'), 1);

CREATE TABLE RESERVATION (
	RES_NUM	NUMBER(10)	PRIMARY KEY,
	RES_RESDATE	DATE	NOT NULL,
	RES_PRICE	NUMBER(10)	NOT NULL,
	RES_STARTTIME	VARCHAR2(20)	NOT NULL,
	RES_ENDTIME	VARCHAR2(20)	NOT NULL,
	MEMBER_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO RESERVATION (RES_NUM, RES_RESDATE, RES_PRICE, RES_STARTTIME, RES_ENDTIME, MEMBER_NUM) 
       VALUES (1, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 100000, '10:00', '12:00', 1);

CREATE TABLE RESLIST (
	RESLIST_INFO	VARCHAR2(20)	NULL,
	RES_NUM	NUMBER(10)	NOT NULL,
	FIELD_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO RESLIST (RESLIST_INFO, RES_NUM, FIELD_NUM) 
       VALUES ('Booking Info', 1, 1);

CREATE TABLE PAYMENT (
	PAY_NUM	NUMBER(10)	PRIMARY KEY,
	APP_PG	VARCHAR2(20)	NOT NULL,
	PAY_DATE	DATE	NOT NULL,
	PAY_PRICE	NUMBER(10)	NOT NULL,
	PAY_BANK	VARCHAR2(20)	NULL,
	RES_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO PAYMENT (PAY_NUM, APP_PG, PAY_DATE, PAY_PRICE, PAY_BANK, RES_NUM) 
    VALUES (1, 'KakaoPay', TO_DATE('2024-05-17', 'YYYY-MM-DD'), 100000, 'KakaoBank', 1);

    DROP TABLE PAYMENT;

CREATE TABLE MATCH (
	MATCH_NUM	NUMBER(10)	PRIMARY KEY,
	MATCH_DATE	VARCHAR2(20)	NOT NULL,
	MATCH_INFO	VARCHAR2(200)	NULL,
	MATCH_TIME	VARCHAR2(20)	NOT NULL,
	CLUB_NUM	NUMBER(10)	NOT NULL,
	FIELD_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO MATCH (MATCH_NUM, MATCH_DATE, MATCH_INFO, MATCH_TIME, CLUB_NUM, FIELD_NUM) 
    VALUES (1, '2024-06-01', 'Friendly match between local teams', '15:00', 1, 1);


CREATE TABLE MATCHBOARD (
	MB_NUM	NUMBER(10)	PRIMARY KEY,
	MB_NAME	VARCHAR2(20)	NOT NULL,
	MB_FILE	VARCHAR2(50)	NOT NULL,
	CLUB_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO MATCHBOARD (MB_NUM, MB_NAME, MB_FILE, CLUB_NUM) 
       VALUES (1, 'Match Schedule', 'schedule.pdf', 1);


CREATE TABLE COMMUNITY (
	COMM_NUM	NUMBER(10)	PRIMARY KEY,
	COMM_CONTENT	VARCHAR2(30)	NULL,
	COMM_DATE	DATE	NULL,
	CLUB_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO COMMUNITY (COMM_NUM, COMM_CONTENT, COMM_DATE, CLUB_NUM) 
       VALUES (1, 'First community post', TO_DATE('2024-05-17', 'YYYY-MM-DD'), 1);


CREATE TABLE BOARD (
	BOARD_NUM	NUMBER(10)	PRIMARY KEY,
	BOARD_NAME	VARCHAR2(30)	NOT NULL,
	BOARD_INFO	VARCHAR2(500)	NULL
);

INSERT INTO BOARD ( BOARD_NUM, BOARD_NAME, BOARD_INFO) 
       VALUES (1, 'General Discussion', 'This board is for general discussion about various topics.');

CREATE TABLE ARTICLE (
	ARTICLE_NUM	NUMBER(10)	PRIMARY KEY,
	ARTICLE_TITLE	VARCHAR2(100)	NOT NULL,
	ARTICLE_CONTENT	VARCHAR2(500)	NOT NULL,
	ARTICLE_DATE	DATE DEFAULT SYSDATE,
	ARTICLE_HITCOUNT	NUMBER(20)	DEFAULT 0,
	MEMBER_NUM	NUMBER(10)	NOT NULL,
	BOARD_NUM	NUMBER(10)	NOT NULL
);

INSERT INTO ARTICLE (ARTICLE_NUM, ARTICLE_TITLE, ARTICLE_CONTENT, ARTICLE_DATE, ARTICLE_HITCOUNT, MEMBER_NUM, BOARD_NUM) 
       VALUES (1, 'Welcome to the Board', 'This is the first article in the general discussion board.', SYSDATE, 0, 1, 1);



CREATE TABLE COMMENTS (
	COMMENT_NUM	NUMBER(10)	PRIMARY KEY,
	COMMENT_CONTENT	VARCHAR2(500)	NOT NULL,
	COMMENT_DATE	DATE	DEFAULT SYSDATE,
	MEMBER_NUM	NUMBER(10)	NOT NULL
);











--------메모--------
-- REC_NO 속성 이름 NUM 변경
ALTER TABLE RECORD_FC RENAME COLUMN REC_NO TO REC_NUM;

SELECT * FROM RECORD_FC;

-- 이메일, 전화번호 등 UK 추가
ALTER TABLE MEMBER ADD (
  CONSTRAINT MEMBER_EMAIL_UK UNIQUE(MEMBER_EMAIL),
  CONSTRAINT MEMBER_PHONE_UK UNIQUE(MEMBER_PHONE)
);

-- 회원 테이블 감독여부(MEMBER_DIR) 속성 디폴트 'N' 추가
ALTER TABLE MEMBER
MODIFY MEMBER_DIR DEFAULT 'N';

-- 이미지 컬럼 추가
-- 멤버 테이블 등번호 컬럼 추가(등번호는 감독이 내팀에서 수정)

-- 전적 승패 CK
ALTER TABLE RECORD_FC ADD (
    CONSTRAINT REC_SCO_CK CHECK (REC_SCO IN ('승', '패'))
);

-- 1. 테이블 구조 수정: REC_SCO 컬럼의 데이터 타입을 CHAR(2)로 변경
ALTER TABLE RECORD_FC
MODIFY REC_SCO CHAR(2);

DELETE FROM RECORD_FC
WHERE REC_SCO = '3-2';








--          Other Key           -------------------------------------------------------------------------------------------------------------------
ALTER TABLE RECORD_FC
  ADD(
    CONSTRAINT REC_CLUB_NUM_FK FOREIGN KEY(CLUB_NUM) REFERENCES CLUB(CLUB_NUM)
);

ALTER TABLE COMMUNITY
  ADD(
    CONSTRAINT COMM_CLUB_NUM_FK FOREIGN KEY(CLUB_NUM) REFERENCES CLUB(CLUB_NUM)
);

ALTER TABLE MATCHBOARD
  ADD(
    CONSTRAINT MB_CLUB_NUM_FK FOREIGN KEY(CLUB_NUM) REFERENCES CLUB(CLUB_NUM)
);

ALTER TABLE MATCH
  ADD(
    CONSTRAINT MATCH_CLUB_NUM_FK FOREIGN KEY(CLUB_NUM) REFERENCES CLUB(CLUB_NUM),
    CONSTRAINT MATCH_FIELD_NUM_FK FOREIGN KEY(FIELD_NUM) REFERENCES FIELD(FIELD_NUM)
);

ALTER TABLE MEMBER
  ADD(
    CONSTRAINT MEMBER_CLUB_NUM_FK FOREIGN KEY(CLUB_NUM) REFERENCES CLUB(CLUB_NUM),
		-- 감독여부 CK
    CONSTRAINT MEMBER_DIR_CK CHECK (MEMBER_DIR IN ('Y', 'N'))
);

ALTER TABLE RESERVATION
  ADD(
    CONSTRAINT RES_MEMBER_NUM_FK FOREIGN KEY(MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM)
);

ALTER TABLE RESLIST
  ADD(
    CONSTRAINT RESLIST_RES_NUM_FK FOREIGN KEY(RES_NUM) REFERENCES RESERVATION(RES_NUM),
    CONSTRAINT RESLIST_FIELD_NUM_FK FOREIGN KEY(FIELD_NUM) REFERENCES FIELD(FIELD_NUM)
);

ALTER TABLE PAYMENT
  ADD(
    CONSTRAINT PAY_RES_NUM_FK FOREIGN KEY(RES_NUM) REFERENCES RESERVATION(RES_NUM)
);

ALTER TABLE ARTICLE
  ADD(
    CONSTRAINT ARTICLE_MEMBER_NUM_FK FOREIGN KEY(MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM),
    CONSTRAINT ARTICLE_BOARD_NUM_FK FOREIGN KEY(BOARD_NUM) REFERENCES BOARD(BOARD_NUM)
);

ALTER TABLE COMMENTS
  ADD(
    CONSTRAINT COMMENTS_MEMBER_NUM_FK FOREIGN KEY(MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM)
);










--      시퀀스                    -------------------------------------------------------------------------
-- GRANT CREATE SEQUENCE
-- TO CHALLAE;

-- 클럽전적 REC_NO
CREATE SEQUENCE REC_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT REC_SEQ.nextval
from DUAL;
--
drop sequence REC_SEQ;


-- 커뮤니티 COMM_NUM
CREATE SEQUENCE COMM_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT COMM_SEQ.nextval
from DUAL;
--
drop sequence COMM_SEQ;


-- 전략판 MB_NUM
CREATE SEQUENCE MB_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT MB_SEQ.nextval
from DUAL;
--
drop sequence MB_SEQ;


-- 클럽 CLUB_NUM
CREATE SEQUENCE CLUB_SEQ
  START WITH 100
  INCREMENT BY 1;
--
SELECT CLUB_SEQ.nextval
from DUAL;
--
drop sequence CLUB_SEQ;


-- 매치 MATCH_NUM
CREATE SEQUENCE MATCH_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT MATCH_SEQ.nextval
from DUAL;
--
drop sequence MATCH_SEQ;


-- 구장 FIELD_NUM
CREATE SEQUENCE FIELD_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT FIELD_SEQ.nextval
from DUAL;
--
drop sequence FIELD_SEQ;


-- 회원 MEMBER_NUM
CREATE SEQUENCE MEMBER_SEQ
  START WITH 1000
  INCREMENT BY 1;
--
SELECT MEMBER_SEQ.nextval
from DUAL;
--
drop sequence MEMBER_SEQ;


-- 예약 RES_NUM
CREATE SEQUENCE RES_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT RES_SEQ.nextval
from DUAL;
--
drop sequence RES_SEQ;


-- 결제 PAY_NUM
CREATE SEQUENCE PAY_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT PAY_SEQ.nextval
from DUAL;
--
drop sequence PAY_SEQ;


-- 게시글 ARTICLE_NUM
CREATE SEQUENCE ARTICLE_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT ARTICLE_SEQ.nextval
from DUAL;
--
drop sequence ARTICLE_SEQ;


-- 게시판 BOARD_NUM
CREATE SEQUENCE BOARD_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT BOARD_SEQ.nextval
from DUAL;
--
drop sequence BOARD_SEQ;


-- 댓글 COMMENT_NUM
CREATE SEQUENCE COMMENT_SEQ
  START WITH 1
  INCREMENT BY 1;
--
SELECT COMMENT_SEQ.nextval
from DUAL;
--
drop sequence COMMENT_SEQ;
