-- 예약
desc reservation;
desc member;
desc reservation;

select *
from R ON M.MEMBER_NUM = R.MEMBER_NUM;

SELECT M.MEMBER_NUM, M.MEMBER_ID, M.MEMBER_NAME, M.MEMBER_PHONE, M.MEMBER_EMAIL,
       R.RES_TIME, R.RES_RESDATE, R.RES_PRICE, R.RES_MEMO
FROM MEMBER M
JOIN RESERVATION R ON M.MEMBER_NUM = R.MEMBER_NUM;


SELECT  M.MEMBER_NAME, M.MEMBER_PHONE,
               R.RES_TIME, R.RES_RESDATE, R.RES_PRICE, R.RES_MEMO
        FROM MEMBER M
                 JOIN RESERVATION R ON M.MEMBER_NUM = R.MEMBER_NUM;
alter TABLE RESERVATION
  drop column res_name;

alter TABLE RESERVATION
  drop column RES_PHONE;


SELECT  M.MEMBER_NAME, M.MEMBER_PHONE,
               R.RES_TIME, R.RES_RESDATE, R.RES_PRICE, R.RES_MEMO
        FROM MEMBER M
                 JOIN RESERVATION R ON M.MEMBER_NUM = R.MEMBER_NUM
        WHERE R.RES_NUM = 15;


 alter TABLE RESERVATION
  modify member_num varchar2(20); 

INSERT INTO RESERVATION(RES_NUM, RES_RESDATE, RES_PRICE, MEMBER_NUM, RES_TIME, RES_MEMO)
VALUES (RES_SEQ.NEXTVAL, TO_DATE('2000-01-01', 'YYYY-MM-DD'), 100, 1005, '01:00-13:00','메모');

 rollback;

 select * from user_sequences;

select * from member;

 select *
 from RESERVATION;

 SELECT FIELD_NUM, FIELD_NAME, FIELD_NEWADDRESS, FIELD_OLDADDRESS, FIELD_PHONE, FIELD_PHOTO, FIELD_SIZE, FIELD_X, FIELD_Y, FIELD_OPENTIME, FIELD_ClOSETIME,FIELD_DAYPRICE, FIELD_ENDPRICE
        FROM FIELD
        WHERE RES_NUM = 1005;

 